//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.TestimonialServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestimonialServiceReference.ITestimonialService")]
    public interface ITestimonialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestimonialService/GetTestimonialSpecificDetails", ReplyAction="http://tempuri.org/ITestimonialService/GetTestimonialSpecificDetailsResponse")]
        string GetTestimonialSpecificDetails(string testimonialCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestimonialService/GetTestimonialSpecificDetails", ReplyAction="http://tempuri.org/ITestimonialService/GetTestimonialSpecificDetailsResponse")]
        System.Threading.Tasks.Task<string> GetTestimonialSpecificDetailsAsync(string testimonialCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestimonialService/DeleteCurrentTestimonial", ReplyAction="http://tempuri.org/ITestimonialService/DeleteCurrentTestimonialResponse")]
        string DeleteCurrentTestimonial(string testimonialCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestimonialService/DeleteCurrentTestimonial", ReplyAction="http://tempuri.org/ITestimonialService/DeleteCurrentTestimonialResponse")]
        System.Threading.Tasks.Task<string> DeleteCurrentTestimonialAsync(string testimonialCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestimonialService/SaveTestimonialDetails", ReplyAction="http://tempuri.org/ITestimonialService/SaveTestimonialDetailsResponse")]
        string SaveTestimonialDetails(string testimonialCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestimonialService/SaveTestimonialDetails", ReplyAction="http://tempuri.org/ITestimonialService/SaveTestimonialDetailsResponse")]
        System.Threading.Tasks.Task<string> SaveTestimonialDetailsAsync(string testimonialCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestimonialService/GetAllTestimonial", ReplyAction="http://tempuri.org/ITestimonialService/GetAllTestimonialResponse")]
        System.Collections.Generic.List<BusinessObjects.TestimonialModel> GetAllTestimonial(string testimonialCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestimonialService/GetAllTestimonial", ReplyAction="http://tempuri.org/ITestimonialService/GetAllTestimonialResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.TestimonialModel>> GetAllTestimonialAsync(string testimonialCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestimonialService/UpdateTestimonialImagePath", ReplyAction="http://tempuri.org/ITestimonialService/UpdateTestimonialImagePathResponse")]
        string UpdateTestimonialImagePath(string testimonialCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestimonialService/UpdateTestimonialImagePath", ReplyAction="http://tempuri.org/ITestimonialService/UpdateTestimonialImagePathResponse")]
        System.Threading.Tasks.Task<string> UpdateTestimonialImagePathAsync(string testimonialCriteria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestimonialServiceChannel : BusinessLogic.TestimonialServiceReference.ITestimonialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestimonialServiceClient : System.ServiceModel.ClientBase<BusinessLogic.TestimonialServiceReference.ITestimonialService>, BusinessLogic.TestimonialServiceReference.ITestimonialService {
        
        public TestimonialServiceClient() {
        }
        
        public TestimonialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestimonialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestimonialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestimonialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTestimonialSpecificDetails(string testimonialCriteria) {
            return base.Channel.GetTestimonialSpecificDetails(testimonialCriteria);
        }
        
        public System.Threading.Tasks.Task<string> GetTestimonialSpecificDetailsAsync(string testimonialCriteria) {
            return base.Channel.GetTestimonialSpecificDetailsAsync(testimonialCriteria);
        }
        
        public string DeleteCurrentTestimonial(string testimonialCriteria) {
            return base.Channel.DeleteCurrentTestimonial(testimonialCriteria);
        }
        
        public System.Threading.Tasks.Task<string> DeleteCurrentTestimonialAsync(string testimonialCriteria) {
            return base.Channel.DeleteCurrentTestimonialAsync(testimonialCriteria);
        }
        
        public string SaveTestimonialDetails(string testimonialCriteria) {
            return base.Channel.SaveTestimonialDetails(testimonialCriteria);
        }
        
        public System.Threading.Tasks.Task<string> SaveTestimonialDetailsAsync(string testimonialCriteria) {
            return base.Channel.SaveTestimonialDetailsAsync(testimonialCriteria);
        }
        
        public System.Collections.Generic.List<BusinessObjects.TestimonialModel> GetAllTestimonial(string testimonialCriteria) {
            return base.Channel.GetAllTestimonial(testimonialCriteria);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.TestimonialModel>> GetAllTestimonialAsync(string testimonialCriteria) {
            return base.Channel.GetAllTestimonialAsync(testimonialCriteria);
        }
        
        public string UpdateTestimonialImagePath(string testimonialCriteria) {
            return base.Channel.UpdateTestimonialImagePath(testimonialCriteria);
        }
        
        public System.Threading.Tasks.Task<string> UpdateTestimonialImagePathAsync(string testimonialCriteria) {
            return base.Channel.UpdateTestimonialImagePathAsync(testimonialCriteria);
        }
    }
}
