//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.ListingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ListingServiceReference.IListingService")]
    public interface IListingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/EditCurrentListing", ReplyAction="http://tempuri.org/IListingService/EditCurrentListingResponse")]
        string EditCurrentListing(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/EditCurrentListing", ReplyAction="http://tempuri.org/IListingService/EditCurrentListingResponse")]
        System.Threading.Tasks.Task<string> EditCurrentListingAsync(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/GetLoanDocuments", ReplyAction="http://tempuri.org/IListingService/GetLoanDocumentsResponse")]
        string GetLoanDocuments(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/GetLoanDocuments", ReplyAction="http://tempuri.org/IListingService/GetLoanDocumentsResponse")]
        System.Threading.Tasks.Task<string> GetLoanDocumentsAsync(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/SaveLoanInformation", ReplyAction="http://tempuri.org/IListingService/SaveLoanInformationResponse")]
        string SaveLoanInformation(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/SaveLoanInformation", ReplyAction="http://tempuri.org/IListingService/SaveLoanInformationResponse")]
        System.Threading.Tasks.Task<string> SaveLoanInformationAsync(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/SavePropertyInformation", ReplyAction="http://tempuri.org/IListingService/SavePropertyInformationResponse")]
        string SavePropertyInformation(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/SavePropertyInformation", ReplyAction="http://tempuri.org/IListingService/SavePropertyInformationResponse")]
        System.Threading.Tasks.Task<string> SavePropertyInformationAsync(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/SaveCommentsInformation", ReplyAction="http://tempuri.org/IListingService/SaveCommentsInformationResponse")]
        string SaveCommentsInformation(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/SaveCommentsInformation", ReplyAction="http://tempuri.org/IListingService/SaveCommentsInformationResponse")]
        System.Threading.Tasks.Task<string> SaveCommentsInformationAsync(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/SaveDocumentsInformation", ReplyAction="http://tempuri.org/IListingService/SaveDocumentsInformationResponse")]
        string SaveDocumentsInformation(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/SaveDocumentsInformation", ReplyAction="http://tempuri.org/IListingService/SaveDocumentsInformationResponse")]
        System.Threading.Tasks.Task<string> SaveDocumentsInformationAsync(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/GetListingLoanTypes", ReplyAction="http://tempuri.org/IListingService/GetListingLoanTypesResponse")]
        System.Collections.Generic.List<BusinessObjects.ListingType> GetListingLoanTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/GetListingLoanTypes", ReplyAction="http://tempuri.org/IListingService/GetListingLoanTypesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.ListingType>> GetListingLoanTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/GetListingDefaultValuesForLoanInformation", ReplyAction="http://tempuri.org/IListingService/GetListingDefaultValuesForLoanInformationRespo" +
            "nse")]
        string GetListingDefaultValuesForLoanInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/GetListingDefaultValuesForLoanInformation", ReplyAction="http://tempuri.org/IListingService/GetListingDefaultValuesForLoanInformationRespo" +
            "nse")]
        System.Threading.Tasks.Task<string> GetListingDefaultValuesForLoanInformationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/GetListingDefaultValuesForPropertyInformation", ReplyAction="http://tempuri.org/IListingService/GetListingDefaultValuesForPropertyInformationR" +
            "esponse")]
        string GetListingDefaultValuesForPropertyInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/GetListingDefaultValuesForPropertyInformation", ReplyAction="http://tempuri.org/IListingService/GetListingDefaultValuesForPropertyInformationR" +
            "esponse")]
        System.Threading.Tasks.Task<string> GetListingDefaultValuesForPropertyInformationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/InsertUpdateListingImagePath", ReplyAction="http://tempuri.org/IListingService/InsertUpdateListingImagePathResponse")]
        string InsertUpdateListingImagePath(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/InsertUpdateListingImagePath", ReplyAction="http://tempuri.org/IListingService/InsertUpdateListingImagePathResponse")]
        System.Threading.Tasks.Task<string> InsertUpdateListingImagePathAsync(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/SaveUploadedListingDocuments", ReplyAction="http://tempuri.org/IListingService/SaveUploadedListingDocumentsResponse")]
        string SaveUploadedListingDocuments(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/SaveUploadedListingDocuments", ReplyAction="http://tempuri.org/IListingService/SaveUploadedListingDocumentsResponse")]
        System.Threading.Tasks.Task<string> SaveUploadedListingDocumentsAsync(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/GetLoanImages", ReplyAction="http://tempuri.org/IListingService/GetLoanImagesResponse")]
        string GetLoanImages(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListingService/GetLoanImages", ReplyAction="http://tempuri.org/IListingService/GetLoanImagesResponse")]
        System.Threading.Tasks.Task<string> GetLoanImagesAsync(string listingCriteria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListingServiceChannel : BusinessLogic.ListingServiceReference.IListingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListingServiceClient : System.ServiceModel.ClientBase<BusinessLogic.ListingServiceReference.IListingService>, BusinessLogic.ListingServiceReference.IListingService {
        
        public ListingServiceClient() {
        }
        
        public ListingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EditCurrentListing(string listingCriteria) {
            return base.Channel.EditCurrentListing(listingCriteria);
        }
        
        public System.Threading.Tasks.Task<string> EditCurrentListingAsync(string listingCriteria) {
            return base.Channel.EditCurrentListingAsync(listingCriteria);
        }
        
        public string GetLoanDocuments(string listingCriteria) {
            return base.Channel.GetLoanDocuments(listingCriteria);
        }
        
        public System.Threading.Tasks.Task<string> GetLoanDocumentsAsync(string listingCriteria) {
            return base.Channel.GetLoanDocumentsAsync(listingCriteria);
        }
        
        public string SaveLoanInformation(string listingCriteria) {
            return base.Channel.SaveLoanInformation(listingCriteria);
        }
        
        public System.Threading.Tasks.Task<string> SaveLoanInformationAsync(string listingCriteria) {
            return base.Channel.SaveLoanInformationAsync(listingCriteria);
        }
        
        public string SavePropertyInformation(string listingCriteria) {
            return base.Channel.SavePropertyInformation(listingCriteria);
        }
        
        public System.Threading.Tasks.Task<string> SavePropertyInformationAsync(string listingCriteria) {
            return base.Channel.SavePropertyInformationAsync(listingCriteria);
        }
        
        public string SaveCommentsInformation(string listingCriteria) {
            return base.Channel.SaveCommentsInformation(listingCriteria);
        }
        
        public System.Threading.Tasks.Task<string> SaveCommentsInformationAsync(string listingCriteria) {
            return base.Channel.SaveCommentsInformationAsync(listingCriteria);
        }
        
        public string SaveDocumentsInformation(string listingCriteria) {
            return base.Channel.SaveDocumentsInformation(listingCriteria);
        }
        
        public System.Threading.Tasks.Task<string> SaveDocumentsInformationAsync(string listingCriteria) {
            return base.Channel.SaveDocumentsInformationAsync(listingCriteria);
        }
        
        public System.Collections.Generic.List<BusinessObjects.ListingType> GetListingLoanTypes() {
            return base.Channel.GetListingLoanTypes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.ListingType>> GetListingLoanTypesAsync() {
            return base.Channel.GetListingLoanTypesAsync();
        }
        
        public string GetListingDefaultValuesForLoanInformation() {
            return base.Channel.GetListingDefaultValuesForLoanInformation();
        }
        
        public System.Threading.Tasks.Task<string> GetListingDefaultValuesForLoanInformationAsync() {
            return base.Channel.GetListingDefaultValuesForLoanInformationAsync();
        }
        
        public string GetListingDefaultValuesForPropertyInformation() {
            return base.Channel.GetListingDefaultValuesForPropertyInformation();
        }
        
        public System.Threading.Tasks.Task<string> GetListingDefaultValuesForPropertyInformationAsync() {
            return base.Channel.GetListingDefaultValuesForPropertyInformationAsync();
        }
        
        public string InsertUpdateListingImagePath(string listingCriteria) {
            return base.Channel.InsertUpdateListingImagePath(listingCriteria);
        }
        
        public System.Threading.Tasks.Task<string> InsertUpdateListingImagePathAsync(string listingCriteria) {
            return base.Channel.InsertUpdateListingImagePathAsync(listingCriteria);
        }
        
        public string SaveUploadedListingDocuments(string listingCriteria) {
            return base.Channel.SaveUploadedListingDocuments(listingCriteria);
        }
        
        public System.Threading.Tasks.Task<string> SaveUploadedListingDocumentsAsync(string listingCriteria) {
            return base.Channel.SaveUploadedListingDocumentsAsync(listingCriteria);
        }
        
        public string GetLoanImages(string listingCriteria) {
            return base.Channel.GetLoanImages(listingCriteria);
        }
        
        public System.Threading.Tasks.Task<string> GetLoanImagesAsync(string listingCriteria) {
            return base.Channel.GetLoanImagesAsync(listingCriteria);
        }
    }
}
