//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.DashboardServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DashboardServiceReference.IDashboardService")]
    public interface IDashboardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardService/GetInvestorDashboard", ReplyAction="http://tempuri.org/IDashboardService/GetInvestorDashboardResponse")]
        string GetInvestorDashboard(string criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardService/GetInvestorDashboard", ReplyAction="http://tempuri.org/IDashboardService/GetInvestorDashboardResponse")]
        System.Threading.Tasks.Task<string> GetInvestorDashboardAsync(string criteria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDashboardServiceChannel : BusinessLogic.DashboardServiceReference.IDashboardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DashboardServiceClient : System.ServiceModel.ClientBase<BusinessLogic.DashboardServiceReference.IDashboardService>, BusinessLogic.DashboardServiceReference.IDashboardService {
        
        public DashboardServiceClient() {
        }
        
        public DashboardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DashboardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashboardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashboardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetInvestorDashboard(string criteria) {
            return base.Channel.GetInvestorDashboard(criteria);
        }
        
        public System.Threading.Tasks.Task<string> GetInvestorDashboardAsync(string criteria) {
            return base.Channel.GetInvestorDashboardAsync(criteria);
        }
    }
}
