//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.HomePageServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HomePageServiceReference.IHomePageService")]
    public interface IHomePageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomePageService/GetLatestNewsandArticlesForHomePage", ReplyAction="http://tempuri.org/IHomePageService/GetLatestNewsandArticlesForHomePageResponse")]
        System.Collections.Generic.List<BusinessObjects.HomePageLatestResources> GetLatestNewsandArticlesForHomePage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomePageService/GetLatestNewsandArticlesForHomePage", ReplyAction="http://tempuri.org/IHomePageService/GetLatestNewsandArticlesForHomePageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.HomePageLatestResources>> GetLatestNewsandArticlesForHomePageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomePageService/GetLatestBrokerListingDetails", ReplyAction="http://tempuri.org/IHomePageService/GetLatestBrokerListingDetailsResponse")]
        System.Collections.Generic.List<BusinessObjects.BrokerListingsModel> GetLatestBrokerListingDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomePageService/GetLatestBrokerListingDetails", ReplyAction="http://tempuri.org/IHomePageService/GetLatestBrokerListingDetailsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.BrokerListingsModel>> GetLatestBrokerListingDetailsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHomePageServiceChannel : BusinessLogic.HomePageServiceReference.IHomePageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HomePageServiceClient : System.ServiceModel.ClientBase<BusinessLogic.HomePageServiceReference.IHomePageService>, BusinessLogic.HomePageServiceReference.IHomePageService {
        
        public HomePageServiceClient() {
        }
        
        public HomePageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HomePageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomePageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomePageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BusinessObjects.HomePageLatestResources> GetLatestNewsandArticlesForHomePage() {
            return base.Channel.GetLatestNewsandArticlesForHomePage();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.HomePageLatestResources>> GetLatestNewsandArticlesForHomePageAsync() {
            return base.Channel.GetLatestNewsandArticlesForHomePageAsync();
        }
        
        public System.Collections.Generic.List<BusinessObjects.BrokerListingsModel> GetLatestBrokerListingDetails() {
            return base.Channel.GetLatestBrokerListingDetails();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.BrokerListingsModel>> GetLatestBrokerListingDetailsAsync() {
            return base.Channel.GetLatestBrokerListingDetailsAsync();
        }
    }
}
