//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.LearnServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LearnServiceReference.ILearnService")]
    public interface ILearnService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/GetExperienceLevel", ReplyAction="http://tempuri.org/ILearnService/GetExperienceLevelResponse")]
        string GetExperienceLevel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/GetExperienceLevel", ReplyAction="http://tempuri.org/ILearnService/GetExperienceLevelResponse")]
        System.Threading.Tasks.Task<string> GetExperienceLevelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/GetTopics", ReplyAction="http://tempuri.org/ILearnService/GetTopicsResponse")]
        string GetTopics(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/GetTopics", ReplyAction="http://tempuri.org/ILearnService/GetTopicsResponse")]
        System.Threading.Tasks.Task<string> GetTopicsAsync(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/GetLearnTypes", ReplyAction="http://tempuri.org/ILearnService/GetLearnTypesResponse")]
        string GetLearnTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/GetLearnTypes", ReplyAction="http://tempuri.org/ILearnService/GetLearnTypesResponse")]
        System.Threading.Tasks.Task<string> GetLearnTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/SaveLearnData", ReplyAction="http://tempuri.org/ILearnService/SaveLearnDataResponse")]
        string SaveLearnData(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/SaveLearnData", ReplyAction="http://tempuri.org/ILearnService/SaveLearnDataResponse")]
        System.Threading.Tasks.Task<string> SaveLearnDataAsync(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/SaveUploadedLearnDocuments", ReplyAction="http://tempuri.org/ILearnService/SaveUploadedLearnDocumentsResponse")]
        string SaveUploadedLearnDocuments(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/SaveUploadedLearnDocuments", ReplyAction="http://tempuri.org/ILearnService/SaveUploadedLearnDocumentsResponse")]
        System.Threading.Tasks.Task<string> SaveUploadedLearnDocumentsAsync(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/InsertUpdateLearnImagePath", ReplyAction="http://tempuri.org/ILearnService/InsertUpdateLearnImagePathResponse")]
        string InsertUpdateLearnImagePath(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/InsertUpdateLearnImagePath", ReplyAction="http://tempuri.org/ILearnService/InsertUpdateLearnImagePathResponse")]
        System.Threading.Tasks.Task<string> InsertUpdateLearnImagePathAsync(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/GetLearnListingDetails", ReplyAction="http://tempuri.org/ILearnService/GetLearnListingDetailsResponse")]
        string GetLearnListingDetails(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/GetLearnListingDetails", ReplyAction="http://tempuri.org/ILearnService/GetLearnListingDetailsResponse")]
        System.Threading.Tasks.Task<string> GetLearnListingDetailsAsync(string listingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/GetSingleLearnDetails", ReplyAction="http://tempuri.org/ILearnService/GetSingleLearnDetailsResponse")]
        string GetSingleLearnDetails(string resourceCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/GetSingleLearnDetails", ReplyAction="http://tempuri.org/ILearnService/GetSingleLearnDetailsResponse")]
        System.Threading.Tasks.Task<string> GetSingleLearnDetailsAsync(string resourceCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/DeleteCurrentResource", ReplyAction="http://tempuri.org/ILearnService/DeleteCurrentResourceResponse")]
        string DeleteCurrentResource(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/DeleteCurrentResource", ReplyAction="http://tempuri.org/ILearnService/DeleteCurrentResourceResponse")]
        System.Threading.Tasks.Task<string> DeleteCurrentResourceAsync(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/EditCurrentResource", ReplyAction="http://tempuri.org/ILearnService/EditCurrentResourceResponse")]
        string EditCurrentResource(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/EditCurrentResource", ReplyAction="http://tempuri.org/ILearnService/EditCurrentResourceResponse")]
        System.Threading.Tasks.Task<string> EditCurrentResourceAsync(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/GetLearnDocuments", ReplyAction="http://tempuri.org/ILearnService/GetLearnDocumentsResponse")]
        string GetLearnDocuments(string learnCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILearnService/GetLearnDocuments", ReplyAction="http://tempuri.org/ILearnService/GetLearnDocumentsResponse")]
        System.Threading.Tasks.Task<string> GetLearnDocumentsAsync(string learnCriteria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILearnServiceChannel : BusinessLogic.LearnServiceReference.ILearnService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LearnServiceClient : System.ServiceModel.ClientBase<BusinessLogic.LearnServiceReference.ILearnService>, BusinessLogic.LearnServiceReference.ILearnService {
        
        public LearnServiceClient() {
        }
        
        public LearnServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LearnServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LearnServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LearnServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetExperienceLevel() {
            return base.Channel.GetExperienceLevel();
        }
        
        public System.Threading.Tasks.Task<string> GetExperienceLevelAsync() {
            return base.Channel.GetExperienceLevelAsync();
        }
        
        public string GetTopics(string learnCriteria) {
            return base.Channel.GetTopics(learnCriteria);
        }
        
        public System.Threading.Tasks.Task<string> GetTopicsAsync(string learnCriteria) {
            return base.Channel.GetTopicsAsync(learnCriteria);
        }
        
        public string GetLearnTypes() {
            return base.Channel.GetLearnTypes();
        }
        
        public System.Threading.Tasks.Task<string> GetLearnTypesAsync() {
            return base.Channel.GetLearnTypesAsync();
        }
        
        public string SaveLearnData(string learnCriteria) {
            return base.Channel.SaveLearnData(learnCriteria);
        }
        
        public System.Threading.Tasks.Task<string> SaveLearnDataAsync(string learnCriteria) {
            return base.Channel.SaveLearnDataAsync(learnCriteria);
        }
        
        public string SaveUploadedLearnDocuments(string learnCriteria) {
            return base.Channel.SaveUploadedLearnDocuments(learnCriteria);
        }
        
        public System.Threading.Tasks.Task<string> SaveUploadedLearnDocumentsAsync(string learnCriteria) {
            return base.Channel.SaveUploadedLearnDocumentsAsync(learnCriteria);
        }
        
        public string InsertUpdateLearnImagePath(string learnCriteria) {
            return base.Channel.InsertUpdateLearnImagePath(learnCriteria);
        }
        
        public System.Threading.Tasks.Task<string> InsertUpdateLearnImagePathAsync(string learnCriteria) {
            return base.Channel.InsertUpdateLearnImagePathAsync(learnCriteria);
        }
        
        public string GetLearnListingDetails(string listingCriteria) {
            return base.Channel.GetLearnListingDetails(listingCriteria);
        }
        
        public System.Threading.Tasks.Task<string> GetLearnListingDetailsAsync(string listingCriteria) {
            return base.Channel.GetLearnListingDetailsAsync(listingCriteria);
        }
        
        public string GetSingleLearnDetails(string resourceCriteria) {
            return base.Channel.GetSingleLearnDetails(resourceCriteria);
        }
        
        public System.Threading.Tasks.Task<string> GetSingleLearnDetailsAsync(string resourceCriteria) {
            return base.Channel.GetSingleLearnDetailsAsync(resourceCriteria);
        }
        
        public string DeleteCurrentResource(string learnCriteria) {
            return base.Channel.DeleteCurrentResource(learnCriteria);
        }
        
        public System.Threading.Tasks.Task<string> DeleteCurrentResourceAsync(string learnCriteria) {
            return base.Channel.DeleteCurrentResourceAsync(learnCriteria);
        }
        
        public string EditCurrentResource(string learnCriteria) {
            return base.Channel.EditCurrentResource(learnCriteria);
        }
        
        public System.Threading.Tasks.Task<string> EditCurrentResourceAsync(string learnCriteria) {
            return base.Channel.EditCurrentResourceAsync(learnCriteria);
        }
        
        public string GetLearnDocuments(string learnCriteria) {
            return base.Channel.GetLearnDocuments(learnCriteria);
        }
        
        public System.Threading.Tasks.Task<string> GetLearnDocumentsAsync(string learnCriteria) {
            return base.Channel.GetLearnDocumentsAsync(learnCriteria);
        }
    }
}
